name: Dummy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
  kuttl-k3d:
    runs-on: ubuntu-latest
    needs: [go-test]
    strategy:
      fail-fast: false
      matrix:
        kubernetes: [v1.25]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: { go-version: 1.x }

      - name: Use bash
        run: |
          sudo ln -s bash /bin/sh.bash
          sudo mv /bin/sh.bash /bin/sh

      - name: Use krew to install the latest kuttl
        run: |
          (
            set -x; cd "$(mktemp -d)" &&
            OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
            ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
            KREW="krew-${OS}_${ARCH}" &&
            curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
            tar zxvf "${KREW}.tar.gz" &&
            ./"${KREW}" install krew
          )
          PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
          echo export "${PATH}" >> ~/.bashrc
          source ~/.bashrc
          kubectl krew install kuttl
          kubectl kuttl version

      - name: Start k3s
        uses: ./.github/actions/k3d
        with:
          k3s-channel: "${{ matrix.kubernetes }}"

      - name: Build CLI
        run: make build

      - name: Create operator namespace
        run: kubectl create namespace postgres-operator

      - name: Install Operator
        run: helm install pgo oci://registry.developers.crunchydata.com/crunchydata/pgo -n postgres-operator

      - name: Run kuttl
        run: |
          source ~/.bashrc
          kubectl kuttl version
          make check-kuttl
