name: Dummy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.x
      - run: make check

      - name: Ensure go.mod is tidy
        run: go mod tidy && git diff --exit-code -- go.mod
  kuttl-k3d:
    runs-on: ubuntu-latest
    needs: [go-test]
    strategy:
      fail-fast: false
      matrix:
        kubernetes: [v1.25, v1.24, v1.23, v1.22, v1.21]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: { go-version: 1.x }

      - name: Start k3s
        uses: ./.github/actions/k3d

      - name: Build CLI
        run: make build

      - name: Create operator namespace
        run: kubectl create namespace postgres-operator

      - name: Install Operator
        run: helm install pgo oci://registry.developers.crunchydata.com/crunchydata/pgo -n postgres-operator

      - name: Use bash
        run: |
          sudo ln -s bash /bin/sh.bash
          sudo mv /bin/sh.bash /bin/sh

      - name: Install kuttl
        run: |
          curl -Lo /usr/local/bin/kubectl-kuttl https://github.com/kudobuilder/kuttl/releases/download/v0.13.0/kubectl-kuttl_0.13.0_linux_x86_64
          chmod +x /usr/local/bin/kubectl-kuttl

      - name: Check resources
        run: free --giga

      - name: Run kuttl
        run: |
          make check-kuttl
